question_count = 2

[[algorithm]]
Name = 'Binary Search'
Type = 'search'
Sorted = true
Selected = true

[[algorithm]]
Name = 'Linear Search'
Type = 'search'
Sorted = false
Selected = true

[[algorithm]]
Name = 'Bubble Sort'
Type = 'sort'
Sorted = false
Selected = true

[[algorithm]]
Name = 'Quick Sort'
Type = 'sort'
Sorted = false
Selected = true

[[algorithm]]
Name = 'Shell Sort'
Type = 'sort'
Sorted = false
Selected = false

[[language]]
Name = 'Javascript'
Selected = true

[[language]]
Name = 'PHP'
Selected = false

[[language]]
Name = 'Python'
Selected = true

[[language]]
Name = 'Go'
Selected = true

[[language]]
Name = 'Bash'
Selected = false
