# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  release:
    types: [ published ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.x'
    
    - name: Install dependencies
      run: go get .

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        # Artifact name
        name: algo_kata-${{github.event.release.tag_name}}
        # A file, directory or wildcard pattern that describes what to upload
        path: |
          algo_kata
          config.toml
